CREATE TABLE elevator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    direction VARCHAR(255),
    current_floor INT,
    capacity INT,
    current_load INT,
    is_moving BOOLEAN
);
